export enum UserRole {
  ADMIN = "ADMIN",
  CONSULTANT = "CONSULTANT",
  CLIENT_ADMIN = "CLIENT_ADMIN",
  CLIENT_USER = "CLIENT_USER",
}

export enum AuditStatus {
  DRAFT = "DRAFT",
  IN_PROGRESS = "IN_PROGRESS",
  REVIEW = "REVIEW",
  COMPLETED = "COMPLETED",
  ARCHIVED = "ARCHIVED",
}

export enum FindingSeverity {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
  INFO = "INFO",
}

export enum FindingCategory {
  AI_READINESS = "AI_READINESS",
  PROCESS_EFFICIENCY = "PROCESS_EFFICIENCY",
  TOOLING = "TOOLING",
  WORKFLOW_AUTOMATION = "WORKFLOW_AUTOMATION",
  DATA_QUALITY = "DATA_QUALITY",
  COST_OPTIMIZATION = "COST_OPTIMIZATION",
}

export enum LSPType {
  TRANSLATION_AGENCY = "TRANSLATION_AGENCY",
  INTERPRETATION_SERVICE = "INTERPRETATION_SERVICE",
  LOCALIZATION_FIRM = "LOCALIZATION_FIRM",
  LANGUAGE_CONSULTANCY = "LANGUAGE_CONSULTANCY",
}

export enum AuditScope {
  FULL = "FULL",
  AI_INTEGRATION = "AI_INTEGRATION",
  PROCESS_AUDIT = "PROCESS_AUDIT",
  TOOL_ASSESSMENT = "TOOL_ASSESSMENT",
  COST_ANALYSIS = "COST_ANALYSIS",
}
